### ISSUE TITLE
Checking if bet is not a number after converting to a number

### ISSUE THREAD

**Issue by shadow-42** [Cannicide/sif-casino#26]
https://github.com/Cannicide/sif-casino/blob/b771557a73d5fca9abe8cddfd042363677f8dd28/blackjack.js#L155

Example:
!blackjack k 

> typeof Number('k') === "number"
true

Fix by by changing to:
typeof args[0] === "number"

**Comment by Cannicide** [comment]
Unfortunately, doing `typeof args[0] === "number"` will not work, because args[0] will always be a String. Since the args array is an array of arguments derived from a user's message, which is a string, each component of the args array (such as args[0]) will also be a String. For example:

!blackjack 51

In this scenario, args[0] would be "51" (in String format) instead of 51. 

Now thinking about it, I could really fix it by removing the typeof altogether and using `!isNan(args[0]) && args[0] != " "`. I believe that would work better, unless I am missing something here, especially since isNan checks if the value inside is not numerical regardless of whether it is a String or a Number variable.

**Comment by Cannicide** [comment]
Although I do agree that the code I currently have for accomplishing this is incorrect, as you pointed out, since it is checking if the bet is a number after converting it into a number.

**Comment by shadow-42** [comment]
Yes isNaN(args[0]) is a better solution.  I ended up with a profile that inserted NaN after the game, so I'm not sure how it was actually ran

**Comment by shadow-42** [comment]
Also instead of doing if/elses; return false checks before continuing can do validation.

      if(isNaN(args[0])){
          message.channel.send({embed: { color: 16711680, description: "Sorry, that is not a valid bet."}});
          return false;
          }

**Comment by Cannicide** [comment]
Fixing (currently only for the jackpot, the rest will be finished later).
